// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Hoverfly-DotNet")]
[assembly: AssemblyCompanyAttribute("Fredrik Normen")]
[assembly: AssemblyDescriptionAttribute("A .Net Library for Hoverfly")]
[assembly: AssemblyCopyrightAttribute("Copyright � 2017")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
