// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Hoverfly-DotNet")]
[assembly: AssemblyCompanyAttribute("Fredrik Normen")]
[assembly: AssemblyDescriptionAttribute("A .Net Library for Hoverfly")]
[assembly: AssemblyCopyrightAttribute("Copyright � 2017")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("0.3.0.0")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyFileVersionAttribute("0.3.0.0")]
